server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
########################--Sample Service 1--##########################################
        - id: sample-service1
          uri: lb://SAMPLE-SERVICE1
          predicates:
            - Path=/sample-service1/**
          filters:
            - RewritePath=/sample-service1/(?<segment>.*), /$\{segment}
        - id: sample-service1
          uri: lb://SAMPLE-SERVICE1
          predicates:
              - Path=/sample-service1/actuator/**
              - Method=GET,POST
          filters:
            - RewritePath=/sample-service1/(?<segment>.*), /$\{segment}
########################--Sample Service 2--############################################
        - id: sample-service2
          uri: lb://SAMPLE-SERVICE2
          predicates:
            - Path=/sample-service2/**
          filters:
            - RewritePath=/sample-service2/(?<segment>.*), /$\{segment}
        - id: sample-service2
          uri: lb://SAMPLE-SERVICE2
          predicates:
            - Path=/sample-service2/actuator/**
            - Method=GET,POST
          filters:
            - RewritePath=/sample-service2/(?<segment>.*), /$\{segment}

      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
    bus:
      destination: test_topic
  kafka:
    bootstrap-servers: http://localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh