server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
  #---cloud bus 설정 추가되는 부분 ---
    bus:
      destination: test_topic
  #--------------------------------
    config:
      server:
        git:
          uri: https://github.com/vmflstm1119/spring-cloud-config-yml.git

#          uri: file://C:\Users\dongjin931-PC\Desktop\git\spring-cloud-config\spring-cloud-config-git #로컬 git repository로 설정하였을 떄
#          username: gitId # git repository가 private일 때
#          password: gitpwd
  kafka:
    bootstrap-servers: http://localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

